package enums;

public enum ReferenceList {

    APRIKOSPURE("APRIKOSPURE", "Baby - "),
    BABYGRÖT("BABYGRÖT", "Baby - "),
    BABYOLJA("BABYOLJA", "Baby - "),
    BABYSEMP("BABYSEMP", "Baby - "),
    BARNMAT("BARNMAT", "Baby - "),
    BARNMATSBURKAR("BARNMATSBURKAR", "Baby - "),
    BEBISGRÖT("BEBISGRÖT", "Baby - "),
    BLÖJOR("BLÖJOR", "Baby - "),
    ERSÄTTNING("ERSÄTTNING", "Baby - "),
    KATRINPLOMMON("KATRINPLOMMON", "Baby - "),
    KATRINPLOMMONPURE("KATRINPLOMMONPURE", "Baby - "),
    KLÄMMIS("KLÄMMIS", "Baby - "),
    KLÄMMISAR("KLÄMMISAR", "Baby - "),
    LIBERO("LIBERO", "Baby - "),
    MAJSKROKAR("MAJSKROKAR", "Baby - "),
    NAPP("NAPP", "Baby - "),
    NAPPAR("NAPPAR", "Baby - "),
    NAPPFLASKNAPPAR("NAPPFLASKNAPPAR", "Baby - "),
    PÄRONPURE("PÄRONPURE", "Baby - "),
    TVÄTTLAPPAR("TVÄTTLAPPAR", "Baby - "),
    VÄLLING("VÄLLING", "Baby - "),
    VÅTSERVETT("VÅTSERVETT", "Baby - "),
    VÅTSERVETTER("VÅTSERVETTER", "Baby - "),
    PLOMMONPURE("PLOMMONPURE", "Baby - "),

    //--------------------------------------- BAKING

    BITSOCKER("BITSOCKER", "Bak - "),
    BLOCKCHOKLAD("BLOCKCHOKLAD", "Bak - "),
    CHIA("CHIA", "Bak - "),
    BAKPULVER("BAKPULVER", "Bak - "),
    CHEERIOS("CHEERIOS", "Bak - "),
    CHERIOS("CHERIOS", "Bak - "),
    CORNFLAKES("CORNFLAKES", "Bak - "),
    CHIAFRÖN("CHIAFRÖN", "Bak - "),
    MUSLI("MUSLI", "Bak - "),
    MÜSLI("MÜSLI", "Bak - "),
    GRAHAMSMJÖL("GRAHAMSMJÖL", "Bak - "),
    FLORSOCKER("FLORSOCKER", "Bak - "),
    HACKADE_MANDLAR("HACKADE MANDLAR", "Bak - "),
    HAVRE("HAVRE", "Bak - "),
    POTATISMJÖL("POTATISMJÖL", "Bak - "),
    HAVREGRYN("HAVREGRYN", "Bak - "),
    VANILJSOCKER("VANILJSOCKER", "Bak - "),
    LINFRÖN("LINFRÖN", "Bak - "),
    BAKCHOKLAD("BAKCHOKLAD", "Bak - "),
    VÅFFELMIX("VÅFFELMIX", "Bak - "),
    VANILJSTÅNG("VANILJSTÅNG", "Bak - "),
    VANILJSÅS("VANILJSÅS", "Bak - "),
    VANILJVISP("VANILJVISP", "Bak - "),
    VETEMJÖL("VETEMJÖL", "Bak - "),
    SÖTMANDEL("SÖTMANDEL", "Bak - "),
    SÖTJÄST("SÖTJÄST", "Bak - "),
    JÄST("JÄST", "Bak - "),
    STRÖBRÖD("STRÖBRÖD", "Bak - "),
    STRÖSOCKER("STRÖSOCKER", "Bak - "),
    SOLROSKÄRNOR("SOLROSKÄRNOR", "Bak - "),
    SOCKER("SOCKER", "Bak - "),
    SKÅLLADE_MANDLAR("SKÅLLADE MANDLAR", "Bak - "),
    SESAMFRÖN("SESAMFRÖN", "Bak - "),
    PUMPAFRÖN("PUMPAFRÖN", "Bak - "),
    PUMPAKÄRNOR("PUMPAKÄRNOR", "Bak - "),
    PÄRLSOCKER("PÄRLSOCKER", "Bak - "),
    MJÖL("MJÖL", "Bak - "),
    MANDEL("MANDEL", "Bak - "),
    MANDELMASSA("MANDELMASSA", "Bak - "),
    MANNAGRYN("MANNAGRYN", "Bak - "),
    KAKAO("KAKAO", "Bak - "),
    MAIZENA("MAIZENA", "Bak - "),
    MAJSMJÖL("MAJSMJÖL", "Bak - "),
    KANELSTÅNG("KANELSTÅNG", "Bak - "),

    // --------------------------------------------------------- BREAD

    BAGUETTE("BAGUETTE", "Bröd - "),
    BARNBRÖD("BARNBRÖD", "Bröd - "),
    BRÖD("BRÖD", "Bröd - "),
    BULLAR("BULLAR", "Bröd - "),
    BURGARBRÖD("BURGARBRÖD", "Bröd - "),
    FRUKOST_BRÖD("FRUKOST BRÖD", "Bröd - "),
    FRUKOSTBRÖD("FRUKOSTBRÖD", "Bröd - "),
    FRUKOSTBRÖD_TILL_BARNEN("FRUKOSTBRÖD TILL BARNEN", "Bröd - "),
    FRULLEBRÖD("FRULLEBRÖD", "Bröd - "),
    HAMBURGARBRÖD("HAMBURGARBRÖD", "Bröd - "),
    HAMBURGARE_BRÖD("HAMBURGARE BRÖD", "Bröd - "),
    HAMBURGERBRÖD("HAMBURGERBRÖD", "Bröd - "),
    HÖNÖKAKA("HÖNÖKAKA", "Bröd - "),
    JULVÖRTBRÖD("JULVÖRTBRÖD", "Bröd - "),
    KORVBRÖD("KORVBRÖD", "Bröd - "),
    LIMPA("LIMPA", "Bröd - "),
    MINIBAGUETTER("MINIBAGUETTER", "Bröd - "),
    PITABRÖD("PITABRÖD", "Bröd - "),
    TUNNBRÖDSRULLE("TUNNBRÖDSRULLE", "Bröd - "),
    TUREBRÖD("TUREBRÖD", "Bröd - "),
    TUREMACKOR("TUREMACKOR", "Bröd - "),
    TUVABRÖD("TUVABRÖD", "Bröd - "),
    TÅRTBOTTNAR("TÅRTBOTTNAR", "Bröd - "),

    // ______________________________________________________ MEAT
    BEA("BEA", "Kött - "),
    BEARNAISE("BEARNAISE", "Kött - "),
    FALUKORV("FALUKORV", "Kött - "),
    GOTTBULLAR("GOTTBULLAR", "Kött - "),
    GÖTTBULLAR("GÖTTBULLAR", "Kött - "),
    KYCKLING("KYCKLING", "Kött - "),
    PASTEJ("PASTEJ", "Kött - "),
    SALAMI("SALAMI", "Kött - "),
    TUREKORV("TUREKORV", "Kött - "),
    VEGANBOLLAR("VEGANBOLLAR", "Kött - "),
    VEGOBOLLAR("VEGOBOLLAR", "Kött - "),
    BURGARE("BURGARE", "Kött - "),
    DENNISKORV("DENNISKORV", "Kött - "),
    FÄRDIGA_BIFFAR("FÄRDIGA BIFFAR", "Kött - "),
    KORV("KORV", "Kött - "),
    LEVERPASTEJ("LEVERPASTEJ", "Kött - "),
    SKAGENRÖRA("SKAGENRÖRA", "Kött - "),
    RÖKT_LAX("RÖKT LAX", "Kött - "),

    //------------------------------------------------------------FROZEN

    DUMPLINGS("DUMPLINGS", "Fryst - "),
    FISK("FISK", "Fryst - "),
    FISKPANETTER("FISKPANETTER", "Fryst - "),
    FISKPINNAR("FISKPINNAR", "Fryst - "),
    FLÄDERSAFT("FLÄDERSAFT", "Fryst - "),
    FORMBAR_FÄRS("FORMBAR FÄRS", "Fryst - "),
    FRYSPIZZA("FRYSPIZZA", "Fryst - "),
    FRYSTA_BLÅBÄR("FRYSTA BLÅBÄR", "Fryst - "),
    FÄRS("FÄRS", "Fryst - "),
    GLASS("GLASS", "Fryst - "),
    GRANATÄPPLEKÄRNOR_FRYSTA("GRANATÄPPLEKÄRNOR FRYSTA", "Fryst - "),
    HAMBURGAREKÖTT("HAMBURGAREKÖTT", "Fryst - "),
    KEBAB("KEBAB", "Fryst - "),
    KOKOSGLASS("KOKOSGLASS", "Fryst - "),
    KÖTTBURGARE("KÖTTBURGARE", "Fryst - "),
    LAX("LAX", "Fryst - "),
    LAXFILÉ("LAXFILÉ", "Fryst - "),
    LAXFILÉR("LAXFILÉR", "Fryst - "),
    MARIESTAD("MARIESTAD", "Fryst - "),
    POTATISBULLAR("POTATISBULLAR", "Fryst - "),
    QUORN("QUORN", "Fryst - "),
    QUORNBITAR("QUORNBITAR", "Fryst - "),
    QUORNFÄRS("QUORNFÄRS", "Fryst - "),
    RÄKOR("RÄKOR", "Fryst - "),
    SMÖRDEG("SMÖRDEG", "Fryst - "),
    SOCKERÄRTOR("SOCKERÄRTOR", "Fryst - "),
    SOJABÖNOR("SOJABÖNOR", "Fryst - "),
    SOJAFÄRS("SOJAFÄRS", "Fryst - "),
    SOJAKORV("SOJAKORV", "Fryst - "),
    TACOFÄRS("TACOFÄRS", "Fryst - "),
    TORSK("TORSK", "Fryst - "),
    VANILJGLASS("VANILJGLASS", "Fryst - "),
    WOKGRÖNSAKER("WOKGRÖNSAKER", "Fryst - "),
    EDAMEBÖNOR("EDAMEBÖNOR", "Fryst - "),
    FRYSMAT("FRYSMAT", "Fryst - "),
    FRYST_SPENAT("FRYST SPENAT", "Fryst - "),
    GRANATÄPPLEKÄRNOR("GRANATÄPPLEKÄRNOR", "Fryst - "),
    OUMPH("OUMPH", "Fryst - "),
    QUORNBITS("QUORNBITS", "Fryst - "),
    SKALADE_RÄKOR("SKALADE RÄKOR", "Fryst - "),
    SKALADE_TOMATER("SKALADE TOMATER", "Fryst - "),
    SKALADETOMATER("SKALADETOMATER", "Fryst - "),
    TORSKFILÉ("TORSKFILÉ", "Fryst - "),
    ÄRTOR("ÄRTOR", "Fryst - "),

    //---------------------------------------------------------------FRESH
    PIZZAKIT("PIZZAKIT", "Färskvaror - "),
    TORTELLINI("TORTELLINI", "Färskvaror - "),
    LASAGNEPLATTOR("LASAGNEPLATTOR", "Färskvaror - "),
    FÄRSK_PASTA("FÄRSK PASTA", "Färskvaror - "),
    FÄRSKPASTA("FÄRSKPASTA", "Färskvaror - "),
    FÄRSK_TAGLIATELLE("FÄRSK TAGLIATELLE", "Färskvaror - "),
    TAGLIATELLE("TAGLIATELLE", "Färskvaror - "),


    //---------------------------------------------------------------HOME

    BADBUBBLOR("BADBUBBLOR", "Hem - "),
    BALLONGER("BALLONGER", "Hem - "),
    BALSAM("BALSAM", "Hem - "),
    BARNTANDBORSTAR("BARNTANDBORSTAR", "Hem - "),
    BARNTANDKRÄM("BARNTANDKRÄM", "Hem - "),
    BINDOR("BINDOR", "Hem - "),
    BLOMMOR("BLOMMOR", "Hem - "),
    CLINOMYN("CLINOMYN", "Hem - "),
    DEO("DEO", "Hem - "),
    DISKBORSTE("DISKBORSTE", "Hem - "),
    DISKHANDSKAR("DISKHANDSKAR", "Hem - "),
    DISKMASKINSSALT("DISKMASKINSSALT", "Hem - "),
    DISKMEDEL("DISKMEDEL", "Hem - "),
    DISKSVAMPAR("DISKSVAMPAR", "Hem - "),
    DISKTRASOR("DISKTRASOR", "Hem - "),
    DUSCH("DUSCH", "Hem - "),
    DUSCHCREME("DUSCHCREME", "Hem - "),
    DUSCHKRÄM("DUSCHKRÄM", "Hem - "),
    DUSCHTVÅL("DUSCHTVÅL", "Hem - "),
    ENGÅNGSHANDSKAR("ENGÅNGSHANDSKAR", "Hem - "),
    FÖNSTERPUTS("FÖNSTERPUTS", "Hem - "),
    HANDSKAR("HANDSKAR", "Hem - "),
    HANDTVÅL("HANDTVÅL", "Hem - "),
    HUSHÅLLSPAPPER("HUSHÅLLSPAPPER", "Hem - "),
    MASKINDISKMEDEL("MASKINDISKMEDEL", "Hem - "),
    NATURDIET("NATURDIET", "Hem - "),
    NÄSDUKAR("NÄSDUKAR", "Hem - "),
    PLACKERS("PLACKERS", "Hem - "),
    PLÅSTER("PLÅSTER", "Hem - "),
    RENGÖRING_MEDEL("RENGÖRING MEDEL", "Hem - "),
    RENGÖRINGSMEDEL("RENGÖRINGSMEDEL", "Hem - "),
    SCHAMPO("SCHAMPO", "Hem - "),
    SCHAMPOO("SCHAMPOO", "Hem - "),
    SENSODYN("SENSODYN", "Hem - "),
    SHAMPOO("SHAMPOO", "Hem - "),
    SKÖLJMEDEL("SKÖLJMEDEL", "Hem - "),
    SÅPA("SÅPA", "Hem - "),
    TAMPONGER("TAMPONGER", "Hem - "),
    TANDBORSTE("TANDBORSTE", "Hem - "),
    TANDBORSTE_HUVUD("TANDBORSTE HUVUD", "Hem - "),
    TANDKRÄM("TANDKRÄM", "Hem - "),
    TANDKRÄM_TURE("TANDKRÄM TURE", "Hem - "),
    TANDKRÄM_TUVA("TANDKRÄM TUVA", "Hem - "),
    TANDKRÄM_TILL_TUVA("TANDKRÄM TILL TUVA", "Hem - "),
    TANDKRÄM_TILL_TURE("TANDKRÄM TILL TURE", "Hem - "),
    TANDTRÅD("TANDTRÅD", "Hem - "),
    TOAPAPPER("TOAPAPPER", "Hem - "),
    TOPS("TOPS", "Hem - "),
    TROSSKYDD("TROSSKYDD", "Hem - "),
    TVÄTTMEDEL("TVÄTTMEDEL", "Hem - "),
    TVÅL("TVÅL", "Hem - "),
    VITTVÄTTMEDEL("VITTVÄTTMEDEL", "Hem - "),


//----------------------------------------------------------------------------- CRACKERS


    SMÅKAKOR("SMÅKAKOR", "Kex - "),
    RISKAKA("RISKAKA", "Kex - "),
    OREOS("OREOS", "Kex - "),
    KAKOR("KAKOR", "Kex - "),
    FIKA("FIKA", "Kex - "),
    KEX("KEX", "Kex - "),
    KNÄCKEBRÖD("KNÄCKEBRÖD", "Kex - "),
    DIGESTIVEKEX("DIGESTIVEKEX", "Kex - "),
    FINNCRISP("FINNCRISP", "Kex - "),


    // -----------------------------------------------------------------------------CANNED


    BBQ_SÅS("BBQ SÅS", "Konserver - "),
    BBQSÅS("BBQSÅS", "Konserver - "),
    BABY_RAY("BABY RAY", "Konserver - "),
    BÖNOR("BÖNOR", "Konserver - "),
    DIJON("DIJON", "Konserver - "),
    DIJONSENAP("DIJONSENAP", "Konserver - "),
    FIKONMARMELAD("FIKONMARMELAD", "Konserver - "),
    FISKBULLAR("FISKBULLAR", "Konserver - "),
    FLYTANDE_HONUNG("FLYTANDE HONUNG", "Konserver - "),
    HALLONSYLT("HALLONSYLT", "Konserver - "),
    ACASIA_HONUNG("ACASIA HONUNG", "Konserver - "),
    APELSINMARMELAD("APELSINMARMELAD", "Konserver - "),
    HONUNG("HONUNG", "Konserver - "),
    INLAGDA_RÖDBETOR("INLAGDA RÖDBETOR", "Konserver - "),
    JOHNNYS_SENAP("JOHNNYS SENAP", "Konserver - "),
    JORDGUBBSSYLT("JORDGUBBSSYLT", "Konserver - "),
    JORDNÖTSSMÖR("JORDNÖTSSMÖR", "Konserver - "),
    KETCHUP("KETCHUP", "Konserver - "),
    KIKÄRTOR("KIKÄRTOR", "Konserver - "),
    KROSSADE_TOMATER("KROSSADE TOMATER", "Konserver - "),
    MAJO("MAJO", "Konserver - "),
    MAJONÄS("MAJONÄS", "Konserver - "),
    MAJS("MAJS", "Konserver - "),
    MARMELAD("MARMELAD", "Konserver - "),
    MAYO("MAYO", "Konserver - "),
    NUTELLA("NUTELLA", "Konserver - "),
    PASSERADE_TOMATER("PASSERADE TOMATER", "Konserver - "),
    RÅRÖRDA_LINGON("RÅRÖRDA LINGON", "Konserver - "),
    SENAP("SENAP", "Konserver - "),
    SENAPSSILL("SENAPSSILL", "Konserver - "),
    SKÄRGÅRDSSILL("SKÄRGÅRDSSILL", "Konserver - "),
    SMÖRGÅSGURKA("SMÖRGÅSGURKA", "Konserver - "),
    SVARTVINBÄRSGELE("SVARTVINBÄRSGELE", "Konserver - "),
    SYLT("SYLT", "Konserver - "),
    TOMATPURE("TOMATPURE", "Konserver - "),
    TOMATPURÉ("TOMATPURÉ", "Konserver - "),
    BABY_RAYS("BABY RAYS", "Konserver - "),
    JORDUBBS_SYLT("JORDUBBS SYLT", "Konserver - "),
    ÄRTSOPPA("ÄRTSOPPA", "Konserver - "),

    // -------------------------------------------------------------- SODA


    ALKOFRI_ÖL("ALKOFRI ÖL", "Läsk - "),
    ÖL("ÖL", "Läsk - "),
    ALKOHOLFRI_ÖL("ALKOHOLFRI ÖL", "Läsk - "),
    ALKOHOLFRITT("ALKOHOLFRITT", "Läsk - "),
    ALKOHOLFRITT_BUBBEL("ALKOHOLFRITT BUBBEL", "Läsk - "),
    COLA("COLA", "Läsk - "),
    GLÖGG("GLÖGG", "Läsk - "),
    JULMUST("JULMUST", "Läsk - "),
    JULÖL("JULÖL", "Läsk - "),
    LÄSK("LÄSK", "Läsk - "),
    SAFT("SAFT", "Läsk - "),
    VINGLÖGG("VINGLÖGG", "Läsk - "),
    COLA_ZERO("COLA ZERO", "Läsk - "),
    COLAZERO("COLAZERO", "Läsk - "),
    ZERO("ZERO", "Läsk - "),

    // --------------------------------------------------------------------- DAIRY

    BAKSMÖR("BAKSMÖR", "Mejerier - "),
    BLÅBÄRSSOPPA("BLÅBÄRSSOPPA", "Mejerier - "),
    BREGOTT("BREGOTT", "Mejerier - "),
    HAVREDRYCK("HAVREDRYCK", "Mejerier - "),
    JUICE("JUICE", "Mejerier - "),
    KESELLA("KESELLA", "Mejerier - "),
    KESO("KESO", "Mejerier - "),
    KVARG("KVARG", "Mejerier - "),
    LAKTOSFRI_CREME_FRAICHE("LAKTOSFRI CREME FRAICHE", "Mejerier - "),
    LAKTOSFRI_VISPGRÄDDE("LAKTOSFRI VISPGRÄDDE", "Mejerier - "),
    LAKTOSFRI_GRÄDDE("LAKTOSFRI GRÄDDE", "Mejerier - "),
    LAKTOSFRI_MJÖLK("LAKTOSFRI MJÖLK", "Mejerier - "),
    MATGRÄDDE("MATGRÄDDE", "Mejerier - "),
    MATLAGNINGSGRÄDDE("MATLAGNINGSGRÄDDE", "Mejerier - "),
    MATLAGNINGSYOGHURT("MATLAGNINGSYOGHURT", "Mejerier - "),
    MATSMÖR("MATSMÖR", "Mejerier - "),
    MJÖLK("MJÖLK", "Mejerier - "),
    MJÖLKFRITT_SMÖR("MJÖLKFRITT SMÖR", "Mejerier - "),
    NYPONSOPPA("NYPONSOPPA", "Mejerier - "),
    OATLY("OATLY", "Mejerier - "),
    RISGRYNSGRÖT("RISGRYNSGRÖT", "Mejerier - "),
    RISIFRUTTI("RISIFRUTTI", "Mejerier - "),
    SMOOTHIE("SMOOTHIE", "Mejerier - "),
    SMÖR("SMÖR", "Mejerier - "),
    SOJAMJÖLK("SOJAMJÖLK", "Mejerier - "),
    TURKISK_YOGHURT("TURKISK YOGHURT", "Mejerier - "),
    VANILJYOGHURT("VANILJYOGHURT", "Mejerier - "),
    VISPGRÄDDE("VISPGRÄDDE", "Mejerier - "),
    BAKPLÅTSPAPPER("BAKPLÅTSPAPPER", "Mejerier - "),
    HAVREGRÄDDE("HAVREGRÄDDE", "Mejerier - "),
    MARGARIN("MARGARIN", "Mejerier - "),
    MATYOGHURT("MATYOGHURT", "Mejerier - "),
    MELLANMJÖLK("MELLANMJÖLK", "Mejerier - "),
    MJÖLKFRITT_MARGARIN("MJÖLKFRITT MARGARIN", "Mejerier - "),
    ÄGG("ÄGG", "Mejerier - "),


    ///-------------------------------------------------------------------CHEESE


    BRIE("BRIE", "Ost - "),
    BRIE_OST("BRIE OST", "Ost - "),
    BRIEOST("BRIEOST", "Ost - "),
    BURGAROST("BURGAROST", "Ost - "),
    CHEDDAROST("CHEDDAROST", "Ost - "),
    CHEVRE("CHEVRE", "Ost - "),
    CHEVREOST("CHEVREOST", "Ost - "),
    FETA("FETA", "Ost - "),
    FETAOST("FETAOST", "Ost - "),
    GETOST("GETOST", "Ost - "),
    GOUDA("GOUDA", "Ost - "),
    GOUDAOST("GOUDAOST", "Ost - "),
    GRUYERE("GRUYERE", "Ost - "),
    GRÄDDOST("GRÄDDOST", "Ost - "),
    HAMBURGEROST("HAMBURGEROST", "Ost - "),
    HALLOUMI("HALLOUMI", "Ost - "),
    KVIBILLE_ÄDELOST("KVIBILLE ÄDELOST", "Ost - "),
    MESSMÖR("MESSMÖR", "Ost - "),
    MOZZARELLA("MOZZARELLA", "Ost - "),
    MÖGELOST_GRÄDD("MÖGELOST GRÄDD", "Ost - "),
    OSTAR("OSTAR", "Ost - "),
    PARMESAN("PARMESAN", "Ost - "),
    PARMESANOST("PARMESANOST", "Ost - "),
    PECORINO("PECORINO", "Ost - "),
    PHILADELPHIA("PHILADELPHIA", "Ost - "),
    PIZZAOST("PIZZAOST", "Ost - "),
    GRATÄNGOST("GRATÄNGOST", "Ost - "),
    PRÄSTOST("PRÄSTOST", "Ost - "),
    TACOOST("TACOOST", "Ost - "),
    VÄSTERBOTTEN("VÄSTERBOTTEN", "Ost - "),
    VÄSTERBOTTENOST("VÄSTERBOTTENOST", "Ost - "),
    CHEDDAR("CHEDDAR", "Ost - "),
    KVIBILLE("KVIBILLE", "Ost - "),
    OST("OST", "Ost - "),
    PHILADELPHIAOST("PHILADELPHIAOST", "Ost - "),
    RIVEN_OST("RIVEN OST", "Ost - "),
    ÄDELOST("ÄDELOST", "Ost - "),

    ////////////////////////////////////////////////////////////////////// PASTA


    ARVORIO_RIS("ARVORIO RIS", "Pasta - "),
    ARVORIORIS("ARVORIORIS", "Pasta - "),
    BALSAMICO("BALSAMICO", "Pasta - "),
    BULGUR("BULGUR", "Pasta - "),
    BULJONG("BULJONG", "Pasta - "),
    BULJONGTÄRNINGAR("BULJONGTÄRNINGAR", "Pasta - "),
    BÖNGRODDAR("BÖNGRODDAR", "Pasta - "),
    CHILIFLAKES("CHILIFLAKES", "Pasta - "),
    CHILIPULVER("CHILIPULVER", "Pasta - "),
    CHIPOTLE("CHIPOTLE", "Pasta - "),
    CITRONKONCENTRAT("CITRONKONCENTRAT", "Pasta - "),
    CITRONSAFT("CITRONSAFT", "Pasta - "),
    CITRONSYRA("CITRONSYRA", "Pasta - "),
    COUSCOUS("COUSCOUS", "Pasta - "),
    CURRY("CURRY", "Pasta - "),
    EKOLOGISKT_RÅGMJÖL("EKOLOGISKT RÅGMJÖL", "Pasta - "),
    FLINGSALT("FLINGSALT", "Pasta - "),
    GARAMASALA("GARAMASALA", "Pasta - "),
    GRÖNSAKSBULJONG("GRÖNSAKSBULJONG", "Pasta - "),
    GRÖNSAKSFOND("GRÖNSAKSFOND", "Pasta - "),
    GRÖT("GRÖT", "Pasta - "),
    GURKMEJA("GURKMEJA", "Pasta - "),
    JALAPENOS("JALAPENOS", "Pasta - "),
    JAPANSK_SOJA("JAPANSK SOJA", "Pasta - "),
    KAFFE("KAFFE", "Pasta - "),
    KAFFEBÖNOR("KAFFEBÖNOR", "Pasta - "),
    KAFFEFILTER("KAFFEFILTER", "Pasta - "),
    KANEL("KANEL", "Pasta - "),
    KAPRIS("KAPRIS", "Pasta - "),
    KARDEMUMMA_MALD("KARDEMUMMA MALD", "Pasta - "),
    KINESISK_SOJA("KINESISK SOJA", "Pasta - "),
    KOKOSFLINGOR("KOKOSFLINGOR", "Pasta - "),
    KOKOSGRÄDDE("KOKOSGRÄDDE", "Pasta - "),
    KOKOSMJÖLK("KOKOSMJÖLK", "Pasta - "),
    KORIANDERPULVER("KORIANDERPULVER", "Pasta - "),
    LIMEJUICE("LIMEJUICE", "Pasta - "),
    LIMESAFT("LIMESAFT", "Pasta - "),
    LINFRÖ("LINFRÖ", "Pasta - "),
    LINSER("LINSER", "Pasta - "),
    LÖKFOND("LÖKFOND", "Pasta - "),
    MAKARONER("MAKARONER", "Pasta - "),
    MATLAGNINGSVIN("MATLAGNINGSVIN", "Pasta - "),
    MUSKOTNÖT("MUSKOTNÖT", "Pasta - "),
    NAAN("NAAN", "Pasta - "),
    NATCHOS("NATCHOS", "Pasta - "),
    NUDLAR("NUDLAR", "Pasta - "),
    OBOY("OBOY", "Pasta - "),
    OLIVER("OLIVER", "Pasta - "),
    OLIVOLJA("OLIVOLJA", "Pasta - "),
    OREGANO("OREGANO", "Pasta - "),
    PASTA("PASTA", "Pasta - "),
    PESTO("PESTO", "Pasta - "),
    PINJENÖTTER("PINJENÖTTER", "Pasta - "),
    QUINOA("QUINOA", "Pasta - "),
    RAPS("RAPS", "Pasta - "),
    RAPSOLJA("RAPSOLJA", "Pasta - "),
    RIS("RIS", "Pasta - "),
    RISNUDLAR("RISNUDLAR", "Pasta - "),
    RUSSIN("RUSSIN", "Pasta - "),
    SALSA("SALSA", "Pasta - "),
    SALT("SALT", "Pasta - "),
    SAMBAL("SAMBAL", "Pasta - "),
    SESAMOLJA("SESAMOLJA", "Pasta - "),
    SNABBMACKARONER("SNABBMACKARONER", "Pasta - "),
    SOJA("SOJA", "Pasta - "),
    SOLTORKADE_TOMATER("SOLTORKADE TOMATER", "Pasta - "),
    SPAGHETTI("SPAGHETTI", "Pasta - "),
    SPISKUMMIN("SPISKUMMIN", "Pasta - "),
    SRIRACHA("SRIRACHA", "Pasta - "),
    SVAMPSOJA("SVAMPSOJA", "Pasta - "),
    SVARTPEPPAR("SVARTPEPPAR", "Pasta - "),
    SVARTPEPPAR_KORN("SVARTPEPPAR KORN", "Pasta - "),
    TACOBRÖD("TACOBRÖD", "Pasta - "),
    TACOCHIPS("TACOCHIPS", "Pasta - "),
    TACOKRYDDA("TACOKRYDDA", "Pasta - "),
    TACOSÅS("TACOSÅS", "Pasta - "),
    TAHINI("TAHINI", "Pasta - "),
    TAPENADE("TAPENADE", "Pasta - "),
    TE("TE", "Pasta - "),
    TERIYAKISÅS("TERIYAKISÅS", "Pasta - "),
    TORTILLABRÖD("TORTILLABRÖD", "Pasta - "),
    VINÄGER("VINÄGER", "Pasta - "),
    VITPEPPAR("VITPEPPAR", "Pasta - "),
    VITTVIN("VITTVIN", "Pasta - "),
    VITTVIN_VINÄGER("VITTVIN VINÄGER", "Pasta - "),
    VITVINSVINÄGER("VITVINSVINÄGER", "Pasta - "),
    BALSAMVINÄGER("BALSAMVINÄGER", "Pasta - "),
    CHILI_SÅS("CHILI SÅS", "Pasta - "),
    CHILISÅS("CHILISÅS", "Pasta - "),
    CHUTNEY("CHUTNEY", "Pasta - "),
    CURRY_PASTA("CURRY-PASTA", "Pasta - "),
    CURRYPASTA("CURRYPASTA", "Pasta - "),
    DINKELMJÖL("DINKELMJÖL", "Pasta - "),
    FARINSOCKER("FARINSOCKER", "Pasta - "),
    JALAPENO("JALAPENO", "Pasta - "),
    KALAMATAOLIVER("KALAMATAOLIVER", "Pasta - "),
    KARDEMUMMAKAPSLAR("KARDEMUMMAKAPSLAR", "Pasta - "),
    KOKOS("KOKOS", "Pasta - "),
    KRYDDPEPPAR("KRYDDPEPPAR", "Pasta - "),
    LIME_BLAD("LIME BLAD", "Pasta - "),
    MASALA("MASALA", "Pasta - "),
    NEJLIKOR("NEJLIKOR", "Pasta - "),
    OLJA("OLJA", "Pasta - "),
    PEPPAR("PEPPAR", "Pasta - "),
    SCHALOTTENLÖKFOND("SCHALOTTENLÖKFOND", "Pasta - "),
    SIRAP("SIRAP", "Pasta - "),
    TORTILLAS("TORTILLAS", "Pasta - "),
    ÄPPELCIDERVINÄGER("ÄPPELCIDERVINÄGER", "Pasta -"),

/////////////////////////////////////////////////////////////////////// KÖK


    SOPPÅSAR("SOPPÅSAR", "Kökssaker - "),
    PLASTFOLIE("PLASTFOLIE", "Kökssaker - "),
    PLASTPÅSAR("PLASTPÅSAR", "Kökssaker - "),
    PÅSAR("PÅSAR", "Kökssaker - "),
    MUFFINSFORMAR("MUFFINSFORMAR", "Kökssaker - "),
    KNÄCKFORMAR("KNÄCKFORMAR", "Kökssaker - "),
    FRYSPÅSAR("FRYSPÅSAR", "Kökssaker - "),
    FOLIE("FOLIE", "Kökssaker - "),
    AVFALLSPÅSE("AVFALLSPÅSE", "Kökssaker - "),
    CUPCAKEFORMAR("CUPCAKEFORMAR", "Kökssaker - "),
    ALUMINIUM_FOLIE("ALUMINIUM FOLIE", "Kökssaker - "),
    ALUMINIUMFOLIE("ALUMINIUMFOLIE", "Kökssaker - "),
    BAJSPÅSE("BAJSPÅSE", "Kökssaker - "),
    BAJSPÅSAR("BAJSPÅSAR", "Kökssaker - "),

    ///////////////////////////////////////////////////////////////////////////////// SNACKS

    CASHEWNÖTTER("CASHEWNÖTTER", "Snacks - "),
    CHIPS("CHIPS", "Snacks - "),
    CHOKLAD("CHOKLAD", "Snacks - "),
    FREDAGSMYS("FREDAGSMYS", "Snacks - "),
    GODIS("GODIS", "Snacks - "),
    GRILLCHIPS("GRILLCHIPS", "Snacks - "),
    HALSTABLETTER("HALSTABLETTER", "Snacks - "),
    JORDNÖTTER("JORDNÖTTER", "Snacks - "),
    NOBLESSE("NOBLESSE", "Snacks - "),
    NÖTTER("NÖTTER", "Snacks - "),
    POPCORN("POPCORN", "Snacks - "),
    PRINGLES("PRINGLES", "Snacks - "),
    SNACKS("SNACKS", "Snacks - "),
    SNARR("SNARR", "Snacks - "),
    VALNÖTSKÄRNOR("VALNÖTSKÄRNOR", "Snacks - "),
    VALNÖTTER("VALNÖTTER", "Snacks - "),

    NATURELL_TOFU("NATURELL TOFU", "Vego - "),
    MIFU("MIFU", "Vego - "),
    TOFU("TOFU", "Vego - "),
    VEGOPASTEJ("VEGOPASTEJ", "Vego - "),

    /////////////////////////////////////////////////////////////////////////////////////////// ÖVRIGT
    ALVEDON("ALVEDON", "Övrigt - "),
    AMNINGSINLÄGG("AMNINGSINLÄGG", "Övrigt - "),
    BLOMJORD("BLOMJORD", "Övrigt - "),
    BLUTSAFT("BLUTSAFT", "Övrigt - "),
    DAMMSUGARPÅSAR("DAMMSUGARPÅSAR", "Övrigt - "),
    GAVISCON("GAVISCON", "Övrigt - "),
    INOTYOL("INOTYOL", "Övrigt - "),
    JORD("JORD", "Övrigt - "),
    MINIDERM("MINIDERM", "Övrigt - "),
    PURELAN("PURELAN", "Övrigt - "),
    SAFFRAN("SAFFRAN", "Övrigt - "),
    SNUS("SNUS", "Övrigt - "),
    TAPIOKA("TAPIOKA", "Övrigt - "),
    TÄNDVÄTSKA("TÄNDVÄTSKA", "Övrigt - "),
    VÄXTNÄRING("VÄXTNÄRING", "Övrigt - "),
    MEDICIN("MEDICIN", "Övrigt - "),
    TAPIOKASTÄRKELSE("TAPIOKASTÄRKELSE", "Övrigt - "),

//////////////////////////////////////////////////////////////////////////////////////////////// GRÖNSAKER


    ÅKERBÄR("ÅKERBÄR", "Grönsaker - "),
    ÅKERBÖN("ÅKERBÖN", "Grönsaker - "),
    ANANAS("ANANAS", "Grönsaker - "),
    ÄNGSSYRA("ÄNGSSYRA", "Grönsaker - "),
    APELSIN("APELSIN", "Grönsaker - "),
    APELSINER("APELSINER", "Grönsaker - "),
    ÄPPLE("ÄPPLE", "Grönsaker - "),
    ÄPPLEN("ÄPPLEN", "Grönsaker - "),
    ARONIABÄR("ARONIABÄR", "Grönsaker - "),
    AUBERGINE("AUBERGINE", "Grönsaker - "),
    AVOKADO("AVOKADO", "Grönsaker - "),
    BABY_SPENAT("BABY SPENAT", "Grönsaker - "),
    BABYSPENAT("BABYSPENAT", "Grönsaker - "),
    BANAN("BANAN", "Grönsaker - "),
    BANANER("BANANER", "Grönsaker - "),
    BÄR("BÄR", "Grönsaker - "),
    BÄRHÄGGMISPEL("BÄRHÄGGMISPEL", "Grönsaker - "),
    BASILIKA_FÄRSK("BASILIKA FÄRSK", "Grönsaker - "),
    BASILIKA("BASILIKA", "Grönsaker - "),
    BATAVIASALLAT("BATAVIASALLAT", "Grönsaker - "),
    BERBERISBÄR("BERBERISBÄR", "Grönsaker - "),
    BIFFTOMAT("BIFFTOMAT", "Grönsaker - "),
    BIGARRÅER("BIGARRÅER", "Grönsaker - "),
    BJÖRNBÄR("BJÖRNBÄR", "Grönsaker - "),
    BLÅBÄR("BLÅBÄR", "Grönsaker - "),
    BLADPERSILJA("BLADPERSILJA", "Grönsaker - "),
    BLADSPENAT("BLADSPENAT", "Grönsaker - "),
    BLÅHALLON("BLÅHALLON", "Grönsaker - "),
    BLOMKÅL("BLOMKÅL", "Grönsaker - "),
    BLOMKÅLSHUVUD("BLOMKÅLSHUVUD", "Grönsaker - "),
    BOCKTÖRNE("BOCKTÖRNE", "Grönsaker - "),
    BONDBÖNOR("BONDBÖNOR", "Grönsaker - "),
    BROCCOLI_FÄRSK("BROCCOLI FÄRSK", "Grönsaker - "),
    BROCCOLI("BROCCOLI", "Grönsaker - "),
    BRYSSELKÅL("BRYSSELKÅL", "Grönsaker - "),
    BRYTBÖNOR("BRYTBÖNOR", "Grönsaker - "),
    BUTTERNUT("BUTTERNUT", "Grönsaker - "),
    CHAMPINJON("CHAMPINJON", "Grönsaker - "),
    CHAMPINJONER("CHAMPINJONER", "Grönsaker - "),
    CHILI("CHILI", "Grönsaker - "),
    CHILIFRUKT("CHILIFRUKT", "Grönsaker - "),
    CHOI("CHOI", "Grönsaker - "),
    CITRON("CITRON", "Grönsaker - "),
    CITRONER("CITRONER", "Grönsaker - "),
    CITRONMELISS("CITRONMELISS", "Grönsaker - "),
    CLEMENTINER("CLEMENTINER", "Grönsaker - "),
    COCKTAIL_TOMAT("COCKTAIL TOMAT", "Grönsaker - "),
    DADLAR("DADLAR", "Grönsaker - "),
    DAGGKÅL("DAGGKÅL", "Grönsaker - "),
    DELIKATESSPOTATIS("DELIKATESSPOTATIS", "Grönsaker - "),
    DILL("DILL", "Grönsaker - "),
    DRAGON("DRAGON", "Grönsaker - "),
    DRUVGURKA("DRUVGURKA", "Grönsaker - "),
    DRUVOR("DRUVOR", "Grönsaker - "),
    EKBLADSSALLAT("EKBLADSSALLAT", "Grönsaker - "),
    ENDIVE("ENDIVE", "Grönsaker - "),
    FÄNKÅL("FÄNKÅL", "Grönsaker - "),
    FÄRSK_BROCCOLI("FÄRSK BROCCOLI", "Grönsaker - "),
    FÄRSKPOTATIS("FÄRSKPOTATIS", "Grönsaker - "),
    FIKON("FIKON", "Grönsaker - "),
    FLÄDERBÄR("FLÄDERBÄR", "Grönsaker - "),
    FLÄDERBLOM("FLÄDERBLOM", "Grönsaker - "),
    FÖRKOKT_MAJS("FÖRKOKT MAJS", "Grönsaker - "),
    FRISÉSALLAT("FRISÉSALLAT", "Grönsaker - "),
    FRUKT("FRUKT", "Grönsaker - "),
    FRUKTER("FRUKTER", "Grönsaker - "),
    GRANATÄPPLE("GRANATÄPPLE", "Grönsaker - "),
    GRÄSLÖK("GRÄSLÖK", "Grönsaker - "),
    GRODDAR("GRODDAR", "Grönsaker - "),
    GRÖN_PAPRIKA("GRÖN PAPRIKA", "Grönsaker - "),
    GRÖNKÅL("GRÖNKÅL", "Grönsaker - "),
    GRÖNSAKER("GRÖNSAKER", "Grönsaker - "),
    GUL_LÖK("GUL LÖK", "Grönsaker - "),
    GUL_PAPRIKA("GUL PAPRIKA", "Grönsaker - "),
    GULBETA("GULBETA", "Grönsaker - "),
    GULLÖK("GULLÖK", "Grönsaker - "),
    GURKA("GURKA", "Grönsaker - "),
    GURKÖRT("GURKÖRT", "Grönsaker - "),
    HABANERO("HABANERO", "Grönsaker - "),
    HALLON("HALLON", "Grönsaker - "),
    HARICOTS_VERTS("HARICOTS VERTS", "Grönsaker - "),
    HARSYRA("HARSYRA", "Grönsaker - "),
    HASSELNÖT("HASSELNÖT", "Grönsaker - "),
    HAVERROT("HAVERROT", "Grönsaker - "),
    HAVTORN("HAVTORN", "Grönsaker - "),
    HJORTRON("HJORTRON", "Grönsaker - "),
    HUVUDSALLAT("HUVUDSALLAT", "Grönsaker - "),
    INGEFÄRA("INGEFÄRA", "Grönsaker - "),
    ISBERGSSALLAD("ISBERGSSALLAD", "Grönsaker - "),
    ISBERGSSALLAT("ISBERGSSALLAT", "Grönsaker - "),
    JALAPEÑO("JALAPEÑO", "Grönsaker - "),
    JORDÄRTSKOCKA("JORDÄRTSKOCKA", "Grönsaker - "),
    JORDGUBBAR("JORDGUBBAR", "Grönsaker - "),
    KÅLRABBI("KÅLRABBI", "Grönsaker - "),
    KÅLROT("KÅLROT", "Grönsaker - "),
    KANTARELLER("KANTARELLER", "Grönsaker - "),
    KAPKRUSBÄR("KAPKRUSBÄR", "Grönsaker - "),
    KARLJOHANSSVAMP("KARLJOHANSSVAMP", "Grönsaker - "),
    KASTANJ("KASTANJ", "Grönsaker - "),
    KINESISK_GRÄSLÖK("KINESISK GRÄSLÖK", "Grönsaker - "),
    KIRSKÅL("KIRSKÅL", "Grönsaker - "),
    KIWI("KIWI", "Grönsaker - "),
    KLEMENTINER("KLEMENTINER", "Grönsaker - "),
    KOMATSUNA("KOMATSUNA", "Grönsaker - "),
    KORIANDER_FÄRSK("KORIANDER FÄRSK", "Grönsaker - "),
    KFÄRSK_KORIANDER("FÄRSK KORIANDER", "Grönsaker - "),
    KORIANDER("KORIANDER", "Grönsaker - "),
    KOROGI("KOROGI", "Grönsaker - "),
    KÖRSBÄRSPLOMMON("KÖRSBÄRSPLOMMON", "Grönsaker - "),
    KÖRSBÄRSTOMAT("KÖRSBÄRSTOMAT", "Grönsaker - "),
    KÖRSBÄRSTOMATER("KÖRSBÄRSTOMATER", "Grönsaker - "),
    KÖRVEL("KÖRVEL", "Grönsaker - "),
    KRASSE("KRASSE", "Grönsaker - "),
    KRIKON("KRIKON", "Grönsaker - "),
    KRONÄRTSKOCKA("KRONÄRTSKOCKA", "Grönsaker - "),
    KRONDILL("KRONDILL", "Grönsaker - "),
    KRUSBÄR("KRUSBÄR", "Grönsaker - "),
    KRUSVINBÄR("KRUSVINBÄR", "Grönsaker - "),
    KVITTEN("KVITTEN", "Grönsaker - "),
    LAGERBLAD("LAGERBLAD", "Grönsaker - "),
    LIBBSTICKA("LIBBSTICKA", "Grönsaker - "),
    LIME("LIME", "Grönsaker - "),
    LINDBLOMMOR("LINDBLOMMOR", "Grönsaker - "),
    LINGON("LINGON", "Grönsaker - "),
    LÖK("LÖK", "Grönsaker - "),
    LÖKTRAV("LÖKTRAV", "Grönsaker - "),
    LUFTLÖK("LUFTLÖK", "Grönsaker - "),
    MACHÉSALLAT("MACHÉSALLAT", "Grönsaker - "),
    MAJROVA("MAJROVA", "Grönsaker - "),
    MAJSKOLVAR("MAJSKOLVAR", "Grönsaker - "),
    MANDARIN("MANDARIN", "Grönsaker - "),
    MANDARINER("MANDARINER", "Grönsaker - "),
    MANDELPOTATIS("MANDELPOTATIS", "Grönsaker - "),
    MANGO("MANGO", "Grönsaker - "),
    MANGOLD("MANGOLD", "Grönsaker - "),
    MÄRGÄRT("MÄRGÄRT", "Grönsaker - "),
    MASKROSBLAD("MASKROSBLAD", "Grönsaker - "),
    MEJRAM("MEJRAM", "Grönsaker - "),
    MELON("MELON", "Grönsaker - "),
    MIZUNA("MIZUNA", "Grönsaker - "),
    MOROT("MOROT", "Grönsaker - "),
    MORÖTTER("MORÖTTER", "Grönsaker - "),
    MURKLOR("MURKLOR", "Grönsaker - "),
    MUSKOTBLOMMA("MUSKOTBLOMMA", "Grönsaker - "),
    MYNTA("MYNTA", "Grönsaker - "),
    NÄSSLOR("NÄSSLOR", "Grönsaker - "),
    NEKTARIN("NEKTARIN", "Grönsaker - "),
    NYPON("NYPON", "Grönsaker - "),
    OKRA("OKRA", "Grönsaker - "),
    OSTRONSKIVLING("OSTRONSKIVLING", "Grönsaker - "),
    PAK_CHOI("PAK CHOI", "Grönsaker - "),
    PALSTERNACKA("PALSTERNACKA", "Grönsaker - "),
    PAPRIKA("PAPRIKA", "Grönsaker - "),
    PÄRLLÖK("PÄRLLÖK", "Grönsaker - "),
    PÄRON("PÄRON", "Grönsaker - "),
    PEPPARROT("PEPPARROT", "Grönsaker - "),
    PERSIKOR("PERSIKOR", "Grönsaker - "),
    PERSILJA_FÄRSK("PERSILJA FÄRSK", "Grönsaker - "),
    PERSILJA("PERSILJA", "Grönsaker - "),
    PERSILJEROT("PERSILJEROT", "Grönsaker - "),
    PIPLÖK("PIPLÖK", "Grönsaker - "),
    PLOCKSALLAT("PLOCKSALLAT", "Grönsaker - "),
    PLOMMON("PLOMMON", "Grönsaker - "),
    POLKABETA("POLKABETA", "Grönsaker - "),
    PORTABELLO("PORTABELLO", "Grönsaker - "),
    PORTLAK("PORTLAK", "Grönsaker - "),
    POTATIS("POTATIS", "Grönsaker - "),
    POTATISLÖK("POTATISLÖK", "Grönsaker - "),
    PUMPA("PUMPA", "Grönsaker - "),
    PURJO("PURJO", "Grönsaker - "),
    PURJOLÖK("PURJOLÖK", "Grönsaker - "),
    RABARBER("RABARBER", "Grönsaker - "),
    RÄDISOR("RÄDISOR", "Grönsaker - "),
    RAMSLÖK("RAMSLÖK", "Grönsaker - "),
    RÄTTIKA("RÄTTIKA", "Grönsaker - "),
    RÖD_LÖK("RÖD LÖK", "Grönsaker - "),
    RÖD_PAPRIKA("RÖD PAPRIKA", "Grönsaker - "),
    RÖD_STEKLÖK("RÖD STEKLÖK", "Grönsaker - "),
    RÖDA_VINBÄR("RÖDA VINBÄR", "Grönsaker - "),
    RÖDBETA("RÖDBETA", "Grönsaker - "),
    RÖDBETOR("RÖDBETOR", "Grönsaker - "),
    RÖDBETSBLAD("RÖDBETSBLAD", "Grönsaker - "),
    RÖDKÅL("RÖDKÅL", "Grönsaker - "),
    RÖDLÖK("RÖDLÖK", "Grönsaker - "),
    ROMANESCO("ROMANESCO", "Grönsaker - "),
    ROMANSALLAT("ROMANSALLAT", "Grönsaker - "),
    RÖNNBÄR("RÖNNBÄR", "Grönsaker - "),
    ROSENKVITTEN("ROSENKVITTEN", "Grönsaker - "),
    ROSÉSALLAT("ROSÉSALLAT", "Grönsaker - "),
    ROSMARIN("ROSMARIN", "Grönsaker - "),
    ROTFRUKTER("ROTFRUKTER", "Grönsaker - "),
    ROTSELLERI("ROTSELLERI", "Grönsaker - "),
    RUCCOLA("RUCCOLA", "Grönsaker - "),
    RUCOLA("RUCOLA", "Grönsaker - "),
    SALLAD("SALLAD", "Grönsaker - "),
    SALLADSKÅL("SALLADSKÅL", "Grönsaker - "),
    SALLADSLÖK("SALLADSLÖK", "Grönsaker - "),
    SALLADSLÖKAR("SALLADSLÖKAR", "Grönsaker - "),
    SALLAT("SALLAT", "Grönsaker - "),
    SALVIA("SALVIA", "Grönsaker - "),
    SAREPTASENAP("SAREPTASENAP", "Grönsaker - "),
    SAVOJKÅL("SAVOJKÅL", "Grönsaker - "),
    SCHALOTTENLÖK("SCHALOTTENLÖK", "Grönsaker - "),
    SELLERI("SELLERI", "Grönsaker - "),
    SHIITAKE("SHIITAKE", "Grönsaker - "),
    SILVERLÖK("SILVERLÖK", "Grönsaker - "),
    SKÄRBÖNOR("SKÄRBÖNOR", "Grönsaker - "),
    SKOGSSVAMP("SKOGSSVAMP", "Grönsaker - "),
    SLÅNBÄR("SLÅNBÄR", "Grönsaker - "),
    SMÅPOTATIS("SMÅPOTATIS", "Grönsaker - "),
    SMÅTOMATER("SMÅTOMATER", "Grönsaker - "),
    SMÖRGÅSKRASSE("SMÖRGÅSKRASSE", "Grönsaker - "),
    SMULTRON("SMULTRON", "Grönsaker - "),
    SOCKERÄRT("SOCKERÄRT", "Grönsaker - "),
    SOCKERROT("SOCKERROT", "Grönsaker - "),
    SOMMARGYLLEN("SOMMARGYLLEN", "Grönsaker - "),
    SÖTPOTATIS("SÖTPOTATIS", "Grönsaker - "),
    SPAGETTIPUMPA("SPAGETTIPUMPA", "Grönsaker - "),
    SPARRIS("SPARRIS", "Grönsaker - "),
    SPARRISSALLAT("SPARRISSALLAT", "Grönsaker - "),
    SPENAT("SPENAT", "Grönsaker - "),
    SPETSKÅL("SPETSKÅL", "Grönsaker - "),
    SQUASH("SQUASH", "Grönsaker - "),
    SURKÖRSBÄR("SURKÖRSBÄR", "Grönsaker - "),
    SVAMP("SVAMP", "Grönsaker - "),
    SVART_MULLBÄR("SVART MULLBÄR", "Grönsaker - "),
    SVARTA_VINBÄR("SVARTA VINBÄR", "Grönsaker - "),
    SVARTA_VINBÄRSBLAD("SVARTA VINBÄRSBLAD", "Grönsaker - "),
    SVARTKÅL("SVARTKÅL", "Grönsaker - "),
    SVARTROT("SVARTROT", "Grönsaker - "),
    SVEDJEROVA("SVEDJEROVA", "Grönsaker - "),
    SYDCIKORIA("SYDCIKORIA", "Grönsaker - "),
    TATSOI("TATSOI", "Grönsaker - "),
    TIMJAN("TIMJAN", "Grönsaker - "),
    TOMAT("TOMAT", "Grönsaker - "),
    TOMATER("TOMATER", "Grönsaker - "),
    TRANBÄR("TRANBÄR", "Grönsaker - "),
    TRATTKANTARELLER("TRATTKANTARELLER", "Grönsaker - "),
    TRYFFEL("TRYFFEL", "Grönsaker - "),
    VALNÖT("VALNÖT", "Grönsaker - "),
    VATTENKRASSE("VATTENKRASSE", "Grönsaker - "),
    VATTENMELON("VATTENMELON", "Grönsaker - "),
    VAXBÖNOR("VAXBÖNOR", "Grönsaker - "),
    VILDAPEL("VILDAPEL", "Grönsaker - "),
    VINDRUVOR("VINDRUVOR", "Grönsaker - "),
    VINTERPOTATIS("VINTERPOTATIS", "Grönsaker - "),
    VIT_LÖK("VIT LÖK", "Grönsaker - "),
    VITBETA("VITBETA", "Grönsaker - "),
    VITKÅL("VITKÅL", "Grönsaker - "),
    VITLÖK("VITLÖK", "Grönsaker - "),
    ZUCCHINI("ZUCCHINI", "Grönsaker - ");

    private String content;
    private String category;

    ReferenceList(String content, String category) {
        this.content = content;
        this.category = category;
    }

    public String getContent() {
        return content;
    }

    public String getCategory() {
        return category;
    }
}
